The BLOCKS SDK: BlockConfigManager Struct Reference
BlockConfigManager Struct Reference
Description
Manages the configuration of blocks.
Public Member Functions
BlockConfigManager (juce::Array< ConfigDescription > defaultConfigOverrides)
void setDeviceIndex (TopologyIndex newDeviceIndex)
void setDeviceComms (PhysicalTopologySource::DeviceConnection *newConn)
juce::int32 getItemValue (BlockConfigId id)
void setItemValue (BlockConfigId id, juce::int32 value)
juce::int32 getItemMin (BlockConfigId id)
void setItemMin (BlockConfigId id, juce::int32 min)
juce::int32 getItemMax (BlockConfigId id)
void setItemMax (BlockConfigId id, juce::int32 max)
bool getItemActive (BlockConfigId id)
void setItemActive (BlockConfigId id, bool isActive)
juce::String getOptionName (BlockConfigId id, juce::uint8 optionIndex)
Block::ConfigMetaData getMetaData (BlockConfigId id)
void resetConfigListActiveStatus ()
bool isUserConfigID (BlockConfigId id)
void setBlockConfig (BlockConfigId id, juce::int32 value)
void requestBlockConfig (BlockConfigId id)
void requestFactoryConfigSync ()
void requestUserConfigSync ()
void handleConfigUpdateMessage (juce::int32 id, juce::int32 value, juce::int32 min, juce::int32 max)
void handleConfigSetMessage (juce::int32 id, juce::int32 value)
Public Attributes
const ConfigDescription defaultConfig [numConfigItems]
Static Public Attributes
static constexpr juce::uint32 numConfigItems = 96
static constexpr const char * midiSettingsGroup = "MIDI Settings"
static constexpr const char * pitchGroup = "Pitch"
static constexpr const char * playGroup = "Play mode"
static constexpr const char * sensitivityGroup = "Sensitivity"
static constexpr const char * rhythmGroup = "Rhythm"
static constexpr const char * coloursGroup = "Colors"
static constexpr const char * mode0Group = "Mode 1"
static constexpr const char * mode1Group = "Mode 2"
static constexpr const char * mode2Group = "Mode 3"
static constexpr const char * mode3Group = "Mode 4"
Classes
struct ConfigDescription
Structure describing a configuration.
Constructor & Destructor Documentation
BlockConfigManager()
BlockConfigManager::BlockConfigManager (juce::Array< ConfigDescription > defaultConfigOverrides)
Member Function Documentation
setDeviceIndex()
void BlockConfigManager::setDeviceIndex (TopologyIndex newDeviceIndex)
setDeviceComms()
void BlockConfigManager::setDeviceComms (PhysicalTopologySource::DeviceConnection * newConn)
getItemValue()
juce::int32 BlockConfigManager::getItemValue (BlockConfigId id)
setItemValue()
void BlockConfigManager::setItemValue (BlockConfigId id, juce::int32 value)
getItemMin()
juce::int32 BlockConfigManager::getItemMin (BlockConfigId id)
setItemMin()
void BlockConfigManager::setItemMin (BlockConfigId id, juce::int32 min)
References min().
getItemMax()
juce::int32 BlockConfigManager::getItemMax (BlockConfigId id)
setItemMax()
void BlockConfigManager::setItemMax (BlockConfigId id, juce::int32 max)
References max().
getItemActive()
bool BlockConfigManager::getItemActive (BlockConfigId id)
setItemActive()
void BlockConfigManager::setItemActive (BlockConfigId id, bool isActive)
getOptionName()
juce::String BlockConfigManager::getOptionName (BlockConfigId id, juce::uint8 optionIndex)
getMetaData()
Block::ConfigMetaData BlockConfigManager::getMetaData (BlockConfigId id)
resetConfigListActiveStatus()
void BlockConfigManager::resetConfigListActiveStatus ()
References roli::BlocksProtocol::key.
isUserConfigID()
bool BlockConfigManager::isUserConfigID (BlockConfigId id)
References roli::BlocksProtocol::user0, and roli::BlocksProtocol::user31.
setBlockConfig()
void BlockConfigManager::setBlockConfig (BlockConfigId id, juce::int32 value)
References BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addConfigSetMessage().
requestBlockConfig()
void BlockConfigManager::requestBlockConfig (BlockConfigId id)
References BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestMessage().
requestFactoryConfigSync()
void BlockConfigManager::requestFactoryConfigSync ()
References BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage().
requestUserConfigSync()
void BlockConfigManager::requestUserConfigSync ()
References BlocksProtocol::HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage().
handleConfigUpdateMessage()
void BlockConfigManager::handleConfigUpdateMessage (juce::int32 id, juce::int32 value, juce::int32 min, juce::int32 max)
References max(), and min().
handleConfigSetMessage()
void BlockConfigManager::handleConfigSetMessage (juce::int32 id, juce::int32 value)
Member Data Documentation
numConfigItems
constexpr juce::uint32 BlockConfigManager::numConfigItems = 96 static constexpr
midiSettingsGroup
constexpr const char* BlockConfigManager::midiSettingsGroup = "MIDI Settings" static constexpr
pitchGroup
constexpr const char* BlockConfigManager::pitchGroup = "Pitch" static constexpr
playGroup
constexpr const char* BlockConfigManager::playGroup = "Play mode" static constexpr
sensitivityGroup
constexpr const char* BlockConfigManager::sensitivityGroup = "Sensitivity" static constexpr
rhythmGroup
constexpr const char* BlockConfigManager::rhythmGroup = "Rhythm" static constexpr
coloursGroup
constexpr const char* BlockConfigManager::coloursGroup = "Colors" static constexpr
mode0Group
constexpr const char* BlockConfigManager::mode0Group = "Mode 1" static constexpr
mode1Group
constexpr const char* BlockConfigManager::mode1Group = "Mode 2" static constexpr
mode2Group
constexpr const char* BlockConfigManager::mode2Group = "Mode 3" static constexpr
mode3Group
constexpr const char* BlockConfigManager::mode3Group = "Mode 4" static constexpr
defaultConfig
const ConfigDescription BlockConfigManager::defaultConfig[numConfigItems]
The documentation for this struct was generated from the following file:
roli_BlockConfigManager.h