The BLOCKS SDK: BlocksProtocol::IntegerWithBitSize< numBits > Struct Template Reference
BlocksProtocol::IntegerWithBitSize< numBits > Struct Template Reference
Description
template<int numBits>
struct BlocksProtocol::IntegerWithBitSize< numBits >
Helper class to define an integer with a specific bit size.
Public Member Functions
IntegerWithBitSize ()=default
IntegerWithBitSize (const IntegerWithBitSize &)=default
IntegerWithBitSize & operator= (const IntegerWithBitSize &)=default
IntegerWithBitSize (juce::uint32 v) noexcept
operator juce::uint32 () const noexcept
juce::uint32 get () const noexcept
juce::uint8 getScaledToByte () const noexcept
float toUnipolarFloat () const noexcept
float toBipolarFloat () const noexcept
Static Public Member Functions
static IntegerWithBitSize fromUnipolarFloat (float value) noexcept
static IntegerWithBitSize fromBipolarFloat (float value) noexcept
Public Attributes
juce::uint32 value = 0
Public Types
enum { bits = numBits , maxValue = static_cast<juce::uint32> ((1ULL << numBits) - 1ULL) }
Constructor & Destructor Documentation
IntegerWithBitSize() [1/3]
template<int numBits> BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize () default
Referenced by BlocksProtocol::IntegerWithBitSize< numBits >::fromBipolarFloat(), and BlocksProtocol::IntegerWithBitSize< numBits >::fromUnipolarFloat().
IntegerWithBitSize() [2/3]
template<int numBits> BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize (const IntegerWithBitSize< numBits > &) default
IntegerWithBitSize() [3/3]
template<int numBits> BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize (juce::uint32 v) noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::maxValue.
Member Function Documentation
operator=()
template<int numBits> IntegerWithBitSize& BlocksProtocol::IntegerWithBitSize< numBits >::operator= (const IntegerWithBitSize< numBits > &) default
operator juce::uint32()
template<int numBits> BlocksProtocol::IntegerWithBitSize< numBits >::operator juce::uint32 () const noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::value.
get()
template<int numBits> juce::uint32 BlocksProtocol::IntegerWithBitSize< numBits >::get () const noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::value.
Referenced by BlocksProtocol::HostPacketDecoder< Handler >::handleButtonDownOrUp(), BlocksProtocol::HostPacketDecoder< Handler >::handleConfigMessage(), BlocksProtocol::HostPacketDecoder< Handler >::handleCustomMessage(), BlocksProtocol::HostPacketDecoder< Handler >::handleTouch(), and BlocksProtocol::HostPacketDecoder< Handler >::handleTouchWithVelocity().
getScaledToByte()
template<int numBits> juce::uint8 BlocksProtocol::IntegerWithBitSize< numBits >::getScaledToByte () const noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::value.
toUnipolarFloat()
template<int numBits> float BlocksProtocol::IntegerWithBitSize< numBits >::toUnipolarFloat () const noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::maxValue, and BlocksProtocol::IntegerWithBitSize< numBits >::value.
toBipolarFloat()
template<int numBits> float BlocksProtocol::IntegerWithBitSize< numBits >::toBipolarFloat () const noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::value.
fromUnipolarFloat()
template<int numBits> static IntegerWithBitSize BlocksProtocol::IntegerWithBitSize< numBits >::fromUnipolarFloat (float value) static noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize(), BlocksProtocol::IntegerWithBitSize< numBits >::maxValue, and BlocksProtocol::IntegerWithBitSize< numBits >::value.
fromBipolarFloat()
template<int numBits> static IntegerWithBitSize BlocksProtocol::IntegerWithBitSize< numBits >::fromBipolarFloat (float value) static noexcept
References BlocksProtocol::IntegerWithBitSize< numBits >::IntegerWithBitSize(), BlocksProtocol::IntegerWithBitSize< numBits >::maxValue, and BlocksProtocol::IntegerWithBitSize< numBits >::value.
Member Enumeration Documentation
anonymous enum
template<int numBits> anonymous enum
Enumerator
bits
maxValue
Member Data Documentation
value
template<int numBits> juce::uint32 BlocksProtocol::IntegerWithBitSize< numBits >::value = 0
Referenced by BlocksProtocol::IntegerWithBitSize< numBits >::fromBipolarFloat(), BlocksProtocol::IntegerWithBitSize< numBits >::fromUnipolarFloat(), BlocksProtocol::IntegerWithBitSize< numBits >::get(), BlocksProtocol::IntegerWithBitSize< numBits >::getScaledToByte(), BlocksProtocol::IntegerWithBitSize< numBits >::operator juce::uint32(), BlocksProtocol::IntegerWithBitSize< numBits >::toBipolarFloat(), and BlocksProtocol::IntegerWithBitSize< numBits >::toUnipolarFloat().
The documentation for this struct was generated from the following file:
roli_BitPackingUtilities.h